# Generated by Django 3.1.7 on 2021-03-06 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_tags'),
        ('blog', '0002_comment'),
    ]

    operations = [
    ]
